// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// 1. Beri tahu Prisma untuk membaca kunci dari .env.local
config({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // 2. Karena file ini dipakai Terminal untuk merombak tabel,
    // kita langsung berikan "Jalur Sepi" (Non-Pooling) sebagai jalurnya.
    url: process.env["POSTGRES_URL_NON_POOLING"],
  },
});
